# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1glqbbwnqzJu2iGbhuDBVMWSVdi4gQXYp
"""



import pandas as pd
import streamlit as st
import pickle
df=pd.read_csv("Cars24.csv")
df=df.drop(['Model','EMI (monthly)','Price'],axis=1)
trfbrand= pickle.load( open('brand.pkl','rb'))
trfyear= pickle.load( open('year.pkl','rb'))
trfloc=pickle.load( open('loc.pkl','rb'))
trffuel=pickle.load( open('fuel.pkl','rb'))
trfgear=pickle.load( open('gear.pkl','rb'))
trfown=pickle.load (open('ownership.pkl','rb'))
pickled_model = pickle.load(open('model.pkl', 'rb'))

brandlist=df['Car Brand'].unique()
yearlist=df['Model Year'].unique()
loclist=df['Location'].unique()
fuellist=df['Fuel'].unique()
gearlist=df['Gear'].unique()
Ownershiplist=df['Ownership'].unique()
def modelpred(brandi,yeari,locai,fueli,geari,owni,kmdriveni):
  arr=[]
  arr.append(trfbrand.transform([brandi])[0])
  arr.append(trfyear.transform([yeari])[0])
  arr.append(trfloc.transform([locai])[0])
  arr.append(trffuel.transform([fueli])[0])
  arr.append(kmdriveni)
  arr.append(trfgear.transform([geari])[0])
  arr.append(trfown.transform([owni])[0])
  
  y = pickled_model.predict([arr])
  return y.reshape(1, -1)
 
  


st.set_page_config(layout="wide")

st.title("Car selling price prediction")


col1, col2,col3 = st.columns(3)

fuel_type = col1.selectbox(" Select fuel type: ",
                     fuellist)

kmsdriven = col1.slider('how much kms driven', 100, 70000, 2000)

gearinp = col2.selectbox(" Select trainsmittion type: ",
                     gearlist)
model=col2.selectbox('which company', brandlist)
ownership=col3.selectbox("owner ship",Ownershiplist)
year=int(col3.text_input('enter year', '2020'))
location =(col3.selectbox('enter location',loclist))



if(st.button("Predict Price")):
    

    price=modelpred(model,year, loca,fuel_type, gearinp,ownership,kmsdriven)
    st.text("precited selling price in lakhs is: "+str(price))
    #Car Brand	Model Year	Location	Fuel	Driven (Kms)	Gear	Ownership
#print(modelpred('Maruti',2019,'Hyderabad','Diesel','Automatic',3,40000))







