# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1glqbbwnqzJu2iGbhuDBVMWSVdi4gQXYp
"""



import pandas as pd
import streamlit as st
from sklearn.preprocessing import LabelEncoder
import pickle
df=pd.read_csv("/content/Cars24.csv")
df=df.drop(['Model','EMI (monthly)','Price'],axis=1)
le1=LabelEncoder()
le1.fit(df['Car Brand'])
le2=LabelEncoder()
le2.fit(df['Model Year'])
le3=LabelEncoder()
le3.fit(df['Location'])
le4=LabelEncoder()
le4.fit(df['Fuel'])
le5=LabelEncoder()
le5.fit(df['Gear'])
le6=LabelEncoder()
le6.fit(df['Ownership'])
brand=df['Car Brand'].unique()
year=df['Model Year'].unique()
loc=df['Location'].unique()
fuel=df['Fuel'].unique()
gear=df['Gear'].unique()
Ownership=df['Ownership'].unique()
def modelpred(brand,year,loca,fuel,gear,own,kmdriven):
  arr=[]
  brand=le1.transform(brand)
  arr.append(brand)
  year=le2.transform(year)
  arr.append(year)
  loca=le3.transform(loca)
  arr.append(loca)
  fuel=le4.append(fuel)
  arr.append(kmdriven)
  gear=le5.transform(gear)
  arr.append(gear)
  own=le6.transform(own)
  arr.append(own)

  
  
  pickled_model = pickle.load(open('/content/model.pkl', 'rb'))
  y= pickled_model.predict(arr)
  return y 
  


st.set_page_config(layout="wide")

st.title("Car selling price prediction")


col1, col2,col3 = st.columns(3)

fuel_type = col1.selectbox(" Select fuel type: ",
                     fuel)

kmsdriven = col1.slider('how much kms driven', 100, 70000, 2000)

gearinp = col2.selectbox(" Select trainsmittion type: ",
                     gear)
model=col2.selectbox('which company', brand)
ownership=col3.selectbox("owner ship",Ownership)
year=int(col3.text_input('enter year', '2020'))
location =(col3.selectbox('enter location',loc))



if(st.button("Predict Price")):
    

    price=modelpred(model,year, loca,fuel_type, gearinp,ownership,kmsdriven)
    st.text("precited selling price in lakhs is: "+str(price))







